name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
          
jobs:
  noetic-devel-ci:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - noetic
        include:
          - docker_image: ubuntu:focal
            ros_distribution: noetic
            ros_version: 1
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Setup directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: ros_ws/src
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@0.3.4
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@0.2.6
        with:
          package-name: natnet_ros_cpp
          target-ros1-distro: ${{ matrix.ros_distribution }}
          skip-tests: true
